### PR TITLE
json changes

### PR DESCRIPTION
**Pull request by maksimlikharev**

### CODE REVIEW

**Comment by maksimlikharev** [comment]
sorry way to early

**Comment by DonMartin76** [comment]
I am currently on vacation and cannot review right now. There a couple of things which need to be done to get Kong 0.10.x compatibility, most prominently that they changed the upstream URL in both property name and to an array, plus some more renamings. They are all mentioned in Kong's release notes, but I just haven't had time to work it through. Achim @achwie can perhaps also pitch in with some more information. Welcome aboard, happy to see you around.

**Comment by maksimlikharev** [comment]
it seems to me changes are widespread throughout the project, kickstarter, kong-adapter and portal-api, those are just obvious places. We have 0.10 cluster and we need 0.10 kong support, for now I'm doing the changes at least to understand the scope.

**Comment by maksimlikharev** [comment]
it seems we have some changes to PR, but Kong 0.10.x is not backward compatible with 0.9, so it will require a branch on your side. Would you willing to create  branch for set of the projects that you have, so we can do PR there.

**Comment by DonMartin76** [comment]
Create a branch on your fork and open the PR against the `next` branch, and we should be fine. Thanks!

**Pull request closed without merging**
